@RideSharingAppApi_HostAddress = http://localhost:5062

# Login via Keycloak (token endpoint)
POST http://localhost:8080/realms/templateAuth/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=testuser&password=testpassword&grant_type=password&client_id=ridesharing-api&client_secret=ridesharing-secret

###

# Request a Ride
POST {{RideSharingAppApi_HostAddress}}/api/v1/rides/request
Content-Type: application/json
Authorization: Bearer 

{
  "origin": "Avenida Paulista, 1000",
  "destination": "Rua Fictícia, 123",
  "userId": "00000000-0000-0000-0000-000000000000"
}

###

# Get Requested Rides
GET {{RideSharingAppApi_HostAddress}}/api/v1/rides/requests
Authorization: Bearer 
Accept: application/json

###

# Create Subscription
POST {{RideSharingAppApi_HostAddress}}/api/v1/subscriptions
Content-Type: application/json
Authorization: Bearer 

{
  "userId": "00000000-0000-0000-0000-000000000000",
  "plan": "premium"
}

###
