@RideSharingAppApi_HostAddress = http://localhost:5062
@apiVersion = 1

### LOGIN
POST {{RideSharingAppApi_HostAddress}}/api/v{{apiVersion}}/login/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "senha123"
}

### REQUEST RIDE
POST {{RideSharingAppApi_HostAddress}}/api/v{{apiVersion}}/rides
Content-Type: application/json
timeout: 1000000000000000000000000000000000000000000000000
Authorization: Bearer

{
  "passengerId": "ce7a2760-364e-4d77-b734-5d0070030ec5",
  "pickupLocation": "Avenida Paulista, 1000",
  "dropoffLocation": "Rua Fictícia, 123"
}

### GET REQUESTED RIDES
GET {{RideSharingAppApi_HostAddress}}/api/v{{apiVersion}}/rides/requests?passengerId=00000000-0000-0000-0000-000000000000&pickupLocation=Avenida%20Paulista,%201000&dropoffLocation=Rua%20Fict%C3%ADcia,%20123
Authorization: Bearer
Accept: application/json

### CREATE SUBSCRIPTION
POST {{RideSharingAppApi_HostAddress}}/api/v{{apiVersion}}/subscriptions
Content-Type: application/json
Authorization: Bearer

{
  "userId": "00000000-0000-0000-0000-000000000000"
}
