name: Python Setup CI

on:
  push:
    paths:
      - 'setup/**'
      - '.github/workflows/ci-setup-python.yml'
  pull_request:
    paths:
      - 'setup/**'
      - '.github/workflows/ci-setup-python.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run setup script (dry run)
        run: |
          python setup.py || true
